name: PIP.Android

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:
  build:
    name: 🛠 Android build
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 16
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace
    
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
    
    - name: build release
      run: ./gradlew assembleRelease
    - name: upload artifact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: pip-kotlin
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Testers
        file: /home/runner/work/pip-kotlin/pip-kotlin/app/build/outputs/apk/debug/app-debug.apk
        notifyTesters: true
        debug: false
